### ISSUE TITLE
how to get ID of created security group

### ISSUE THREAD

**Issue by hamsterksu** [cloudify-cosmo/cloudify-openstack-plugin#155]
Hi everybody,

i want to link my security groups with `remote_group_id`
```yaml
 - direction: ingress
    ethertype: IPv4
    port_range_min: 1
    port_range_max: 65535
    protocol: tcp
    remote_group_id: { get_attribute: [origin_security_group, id ] }
```
but it does not work just throws internal error

i tried to use `remote_group_node: origin_security_group` but it does not work too.

So how to use any group in security group rule?
