### ISSUE TITLE
How to boot an instance with configdrive on ?

### ISSUE THREAD

**Issue by thomnico** [cloudify-cosmo/cloudify-openstack-plugin#157]
I have been searching in the code how to boot with config-drive on ( a necessity for some NfVs) and could not find anything.

Can we have a boolean parameter that allows using config drive when calling nova boot API ???

**Comment by idanmo** [comment]
Hi,
Have you tried something like:

```yaml
node_templates:
  instance:
    type: cloudify.openstack.nodes.Server
    properties:
      config_drive: true
```
