### ISSUE TITLE
How to disable network security ?

### ISSUE THREAD

**Issue by thomnico** [cloudify-cosmo/cloudify-openstack-plugin#158]
In NfV realm many of the VMs will be routers, hence the arp filtering must be disabled.

How can I get a nonfiltered port in Cloudify to give to my VMs ??

**Comment by idanmo** [comment]
Is this an operating system setting or Neutron?

**Comment by michalskalski** [comment]
```
  VNF_port:
    type: cloudify.openstack.nodes.Port
    properties:
    interfaces:
      cloudify.interfaces.lifecycle:
        create:
          inputs:
            args:
              port_security_enabled: false
```
