### ISSUE TITLE
Rename API payload properties names to resource_config.

### ISSUE THREAD

**Issue by EarthmanT** [cloudify-cosmo/cloudify-openstack-plugin#211]
For example:

```
  cloudify.openstack.nodes.Server:
    derived_from: cloudify.nodes.Compute
    properties:
      server:
        default: {}
        description: >
          The keypair object as described in OpenStack compute API (create server method):
          https://developer.openstack.org/api-ref/compute/#servers-servers
```

Should be changed to:
```
  cloudify.openstack.nodes.Server:
    derived_from: cloudify.nodes.Compute
    properties:
      resource_config:
        default: {}
        description: >
          The keypair object as described in OpenStack compute API (create server method):
          https://developer.openstack.org/api-ref/compute/#servers-servers
```
