### ISSUE TITLE
Cannot define networks in properties of nodes.Server

### ISSUE THREAD

**Issue by trihoangvo** [cloudify-cosmo/cloudify-openstack-plugin#229]
Environment:
- Cloudify Manager 3.4.1
- OpenStack Plugin 2.7.4.

In the Openstack Plugin document [1], you say we can specify a key-value configuration in the "properties" for the Server as in the OpenStack Rest API [2]. However, it does not work. For example, I specify a "networks" the following blueprint:

```
host:
  type: cloudify.openstack.nodes.Server
  properties:
    server:
      networks:
        - uuid: 'f4b0b5c1-9e41-4df9-bb29-beb873572f53'
          fixed_ip: '10.0.0.3'
```

The REST request (to create the server) has no information about the network as I expected:

```
DEBUG: REQ: curl -g -i -X POST https://...com/v2/ab2c6f48c344402db70a8041847b0076/servers -H "User-Agent: python-nov
aclient" -H "Content-Type: application/json" -H "Accept: application/json" -H "X-Auth-Token: {SHA1}..." -d '{"server": {"name": "server_helloworld_
host_a9k0ha", "imageRef": "...", "flavorRef": "computev1-1", "user_data": "...", "max_count": 1, "min_count": 1, "metadata": {"blueprint_version": "v1"}}}'
2018-05-08 09:58:47,810 [ad9ec1c0-9ee0-4e2b-8349-75692bb6b4ea]
```
```
RESP BODY: {"badRequest":{"message":"Multiple possible networks found, use a Network ID to be more specific.","code":"400"}}
```

[1] https://docs.cloudify.co/4.3.0/developer/official_plugins/openstack/
[2] https://developer.openstack.org/api-ref/compute/#create-server

**Comment by EarthmanT** [comment]
Hi,

In the following blueprint I reference `networks: [{uuid: xxx, fixed_ip: xxx}]`. During the execution I see the API data in the following log.

```
  host:
    type: cloudify.openstack.nodes.Server
    properties:
      openstack_config: *openstack_config
      agent_config:
        network: { get_input: manager_network }
        user: { get_input: agent_user }
        install_method: init_script
        port: 22
        key: { get_input: agent_key_private }
      server:
        meta:
          blueprint_version: v1
        key_name: ''
        image: { get_input: image }
        flavor: { get_input: flavor }
        networks:
        - uuid: { get_attribute: [ public_network, external_id ] }
          fixed_ip: { get_attribute: [ port, fixed_ip_address ] }
    relationships:
    - type: cloudify.relationships.contained_in
      target: public_network
    - type: cloudify.relationships.depends_on
      target: port
    - type: cloudify.relationships.depends_on
      target: cloudify_host_cloud_config

  port:
    type: cloudify.openstack.nodes.Port
    properties:
      openstack_config: *openstack_config
    relationships:
    - type: cloudify.relationships.contained_in
      target: public_network
    - type: cloudify.relationships.depends_on
      target: public_subnet
    - type: cloudify.openstack.port_connected_to_security_group
      target: security_group
    - type: cloudify.openstack.port_connected_to_floating_ip
      target: ip

```



```
2018 - 05 - 09 10: 30: 03.711 LOG < hw1 > [host_qjp3rs.create] INFO: Creating VM with parameters: {
	u 'meta': {
		u 'blueprint_version': u 'v1'
	},
	'name': 'server_hw1_host_qjp3rs',
	'nics': [{
		'port-id': u 'fb037912-c93a-49a4-b46b-7f63ff103464'
	}],
	u 'key_name': u '',
	u 'image': u 'e41430f7-9131-495b-927f-e7dc4b8994c8',
	u 'flavor': u '2',
	'security_groups': [],
	u 'networks': [{
		u 'fixed_ip': u '10.10.0.6',
		u 'uuid': u 'f9e806a6-86b8-41c2-b8a5-96073ad9808a'
	}]
}
```

What is different in our approaches?

**Comment by trihoangvo** [comment]
HI @EarthmanT 

In your blueprint, your "host" has a relationship with the network "public_network". In my blueprint, I tried to define a "host" with the "networks" in the properties only (no relationship with a network).

Since the OpenStack document says we can boot a VM in a given "networks", it is really nice to do so. Because the blueprint is short and easy to read when you have multiple VMs / networks. Of course, I can define a relationships for each VM.

**Comment by EarthmanT** [comment]
If the network `f4b0b5c1-9e41-4df9-bb29-beb873572f53` exists in your Openstack tenant, then you should not need that relationship there.

**Comment by trihoangvo** [comment]
Can we boot a VM with a fixed ip with this simple definition:
```
host:
  type: cloudify.openstack.nodes.Server
  properties:
    server:
      networks:
        - uuid: 'f4b0b5c1-9e41-4df9-bb29-beb873572f53'
          fixed_ip: '10.0.0.3'
```
Create a server in a given "networks" is supported:
https://developer.openstack.org/api-ref/compute/#create-server
