### ISSUE TITLE
Relationship port_connected_to_security_group not work

### ISSUE THREAD

**Issue by trihoangvo** [cloudify-cosmo/cloudify-openstack-plugin#230]
Environment:
- Cloudify Manager 3.4.1.
- OpenStack Plugin 2.7.4.

I use the "helloworld" blueprint. It creates a port with a security group:
```
  port:
    type: cloudify.openstack.nodes.Port
    properties:
      fixed_ip: 10.0.0.3
    relationships:
      - type: cloudify.relationships.contained_in
        target: private_network
      - type: cloudify.relationships.depends_on
        target: private_subnet
      - type: cloudify.openstack.port_connected_to_floating_ip
        target: ip
      - type: cloudify.openstack.port_connected_to_security_group
        target: security_group

  security_group:
    type: cloudify.openstack.nodes.SecurityGroup
    properties:
      security_group:
        description: generic security group
      rules:
        - remote_ip_prefix: 0.0.0.0/0
          port:
            get_input: webserver_port
```
The security group is created successfully. But the port fails with error "**Port must be in one SecurityGroup**" even we already defined the relationship between the port and the security group.

```
2018-05-08 12:17:33,828 [keystoneauth.session] DEBUG: REQ: curl -g -i -X POST https://.../v2.0/ports.json -H "User-Agent: python-neutronclient" -H "Content-Type
: application/json" -H "Accept: application/json" -H "X-Auth-Token: {SHA1}..." -d '{"port": {"network_id": "f4b0b5c1-...", 
"fixed_ips": [{"subnet_id": "d2bb51da-...", "ip_address": "10.0.0.3"}], "name": "port_helloworld_port_axo7fz", "security_groups": []}}'

RESP BODY: {"NeutronError":{"message":"Port must be in one SecurityGroup.","type":"InvalidInput","detail":""}}
```

**Comment by EarthmanT** [comment]
Hello,
There are some issues with the information that you have provided:

1. This error seems to be related a different port than the one provided. You provided a node_template `port`. When no name is provided, the openstack plugin generates the name off of the node_template name. So I would expect to see an error for `port_axo7fz`. Instead, the error message references a port named `port_helloworld_port_axo7fz`. This is not the same port. Can you double check your blueprint and make sure that you do not have another port node_template `port_helloworld_port` that is not actually connected to the security group?

1. I'm speculating that you might have another blueprint that creates `port_helloworld_port`, and now you want to refer to that port in a new blueprint, and in this new blueprint you want to connect a port to an existing port. You would need to specify that this port is an existing resource (see below). At this point, it's worth pointing out that attaching a security group or floating IP to an existing port will require that you are using a network configuration where such operations are valid. That would require more a more detailed look at your blueprint YAML(s).

```
  port:
    type: cloudify.openstack.nodes.Port
    properties:
      use_external_resource: true
      resource_id: port_helloworld_port_axo7fz
      fixed_ip: 10.0.0.3
    relationships:
      - type: cloudify.relationships.contained_in
        target: private_network
      - type: cloudify.relationships.depends_on
        target: private_subnet
      - type: cloudify.openstack.port_connected_to_floating_ip
        target: ip
      - type: cloudify.openstack.port_connected_to_security_group
        target: security_group
```

So check those suggestions.

**Comment by trihoangvo** [comment]
Hi @EarthmanT 

No, I create a **new** port in an **existing** network with an **existing** security group. The full blueprint is as simple as below:

```
node_templates:
  port:
    type: cloudify.openstack.nodes.Port
    properties:
      openstack_config: *openstack_config
      fixed_ip: 10.0.0.4
    relationships:
      - type: cloudify.relationships.contained_in
        target: private_network
      - type: cloudify.relationships.depends_on
        target: private_subnet
      - type: cloudify.openstack.port_connected_to_security_group
        target: security_group
  security_group:
    type: cloudify.openstack.nodes.SecurityGroup
    properties:
      openstack_config: *openstack_config
      use_external_resource: true
      resource_id: cloudify
  private_network:
    type: cloudify.openstack.nodes.Network
    properties:
      openstack_config: *openstack_config
      use_external_resource: true
      resource_id: f4b0b5c1-...
  private_subnet:
    type: cloudify.openstack.nodes.Subnet
    properties:
      openstack_config: *openstack_config
      use_external_resource: true
      resource_id: d2bb51da-...
    relationships:
      - type: cloudify.relationships.contained_in
        target: private_network
```
In the following request, we notice the list of security groups are empty:
```
DEBUG: REQ: curl -g -i -X POST https://vpc.eu-de.otc.t-systems.com/v2.0/ports.json -H "User-Agent: python-neutronclient" -H "Content-Type: a
pplication/json" -H "Accept: application/json" -H "X-Auth-Token: {SHA1}..." -d '{"port": {"network_id": "f4b0b5c1-...", "fixed
_ips": [{"subnet_id": "d2bb51da-...", "ip_address": "10.0.0.4"}], "name": "port_helloworld_9n7nty", "security_groups": []}}'

RESP BODY: {"NeutronError":{"message":"Port must be in one SecurityGroup.","type":"InvalidInput","detail":""}}
```
