### ISSUE TITLE
server.start() doesn't have defaults, making it hard to subtype

### ISSUE THREAD

**Issue by isaac-s** [cloudify-cosmo/cloudify-openstack-plugin#271]
https://github.com/cloudify-cosmo/cloudify-openstack-plugin/blob/2.11.0/nova_plugin/server.py#L406

The `start_retry_interval` and `private_key_path` inputs have defaults in `plugin.yaml`, but don't have defaults in the function's signature.

If someone wants to subtype `openstack.Server` to apply a default to `private_key_path`, they should be able to do this:

```
start:
  implementation: openstack.nova_plugin.server.start
  inputs:
    private_key_path:
      default: { get_secret: my_key }
```

But they can't. That's because Cloudify's DSL replaces the entire `start` block, so only `private_key_path` would be sent to the operation. That would break the plugin because there are no defaults in the function's signature.
